<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\kruGL.Native\kruGL.Native.csproj" />
    <ProjectReference Include="..\kruGL.OpenGL\kruGL.OpenGL.csproj" />
    <ProjectReference Include="..\kruGL.Platform\kruGL.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GLFW-Net" Version="3.3.1" />
    <PackageReference Include="GLFW" Version="3.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Target Name="CopyGlfwNativeDll" AfterTargets="Build">
    <PropertyGroup>
      <GlfwNativeSource>$(NuGetPackageRoot)glfw/3.4.0/build/native/bin/dynamic/v143/x64/glfw3.dll</GlfwNativeSource>
      <GlfwNativeTarget>$(OutDir)glfw.dll</GlfwNativeTarget>
    </PropertyGroup>

    <Copy SourceFiles="$(GlfwNativeSource)"
          DestinationFiles="$(GlfwNativeTarget)"
          SkipUnchangedFiles="true"
          Condition="Exists('$(GlfwNativeSource)')" />
  </Target>

</Project>
