<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\kruGL.Abstractions\kruGL.Abstractions.csproj" />
    <ProjectReference Include="..\kruGL.Core\kruGL.Core.csproj" />
    <ProjectReference Include="..\kruGL.Native\kruGL.Native.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageId>kruGL.OpenGL</PackageId>
    <Description>Low-level OpenGL API wrapper for kruGL.</Description>
    <PackageOutputPath>../artifacts/packages</PackageOutputPath>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" Link="README.md" />
  </ItemGroup>

</Project>
