<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\kruGL.OpenGL\kruGL.OpenGL.csproj" />
    <ProjectReference Include="..\kruGL.Platform\kruGL.Platform.csproj" />
    <ProjectReference Include="..\kruGL.Platform.Glfw\kruGL.Platform.Glfw.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
