<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>kruGL.Native</PackageId>
    <Description>Native loading helpers for kruGL.</Description>
    <PackageOutputPath>../artifacts/packages</PackageOutputPath>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" Link="README.md" />
  </ItemGroup>

</Project>
